"""
Data models for GWAS Catalog API request parameters and response structures.
"""

from gwascatalog.mcp.models.params import (
    URI,
    AccessionId,
    AncestralGroup,
    AssociationId,
    AssociationSortKeyField,
    Cohort,
    DiseaseTrait,
    EfoId,
    EfoTrait,
    FullPValueSet,
    GetAssociationsParams,
    GetStudiesParams,
    GetTraitsParams,
    GxE,
    MappedGene,
    PageField,
    PubmedId,
    RsId,
    ShowChildTrait,
    SizeField,
    SortDirectionField,
    StudySortKeyField,
    TraitSortKeyField,
)
from gwascatalog.mcp.models.results import (
    AncestryResult,
    AssociationResult,
    PageSummary,
    StudyResult,
    ToolResponse,
    TraitResult,
)

__all__ = [
    "AncestryResult",
    "AssociationResult",
    "GetAssociationsParams",
    "GetStudiesParams",
    "GetTraitsParams",
    "PageSummary",
    "StudyResult",
    "ToolResponse",
    "TraitResult",
    # types
    "AccessionId",
    "AncestralGroup",
    "AssociationId",
    "AssociationSortKeyField",
    "Cohort",
    "DiseaseTrait",
    "EfoId",
    "EfoTrait",
    "FullPValueSet",
    "GxE",
    "MappedGene",
    "PageField",
    "PubmedId",
    "RsId",
    "ShowChildTrait",
    "SizeField",
    "SortDirectionField",
    "StudySortKeyField",
    "TraitSortKeyField",
    "URI",
]
